name: Deploy PostgreSQL to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy PostgreSQL container on EC2 without saving SSH key
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      run: |
        echo "$EC2_SSH_KEY" | ssh \
          -o StrictHostKeyChecking=no \
          -i /dev/stdin \
          $EC2_USER@$EC2_HOST \
          "docker stop postgresql-dev || true && \
           docker rm postgresql-dev || true && \
           docker run -d \
             --name postgresql-dev \
             -e POSTGRES_USER=${POSTGRES_USER} \
             -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
             -e POSTGRES_DB=${POSTGRES_DB} \
             -p 5432:5432 \
             postgres:15"
